import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api, BillingPlans } from '../api'
import { useAuth } from '../auth'

const money = (amount: number, currency: string) => new Intl.NumberFormat('es', { style:'currency', currency, maximumFractionDigits:amount%100===0?0:2 }).format(amount/100)

export function Pricing() {
  const [plans,setPlans]=useState<BillingPlans|null>(null); const [busy,setBusy]=useState(''); const [error,setError]=useState(''); const [promotionCode,setPromotionCode]=useState(''); const [promoMessage,setPromoMessage]=useState(''); const { user, refresh }=useAuth(); const navigate=useNavigate()
  useEffect(()=>{ api.plans().then(setPlans).catch(()=>setPlans(null)) },[])
  async function buy(plan:'studio'|'cloud_monthly'|'cloud_annual') { if(!user){navigate('/register?next=/pricing');return} setBusy(plan);setError('');try{window.location.assign((await api.checkout(plan,promotionCode)).url)}catch(e){setError(e instanceof Error?e.message:'No pudimos iniciar el pago.')}finally{setBusy('')} }
  async function redeem() { if(!user){navigate('/register?next=/pricing');return} setBusy('promo');setError('');setPromoMessage('');try{await api.redeemPromotion(promotionCode);await refresh();navigate('/account?promo=redeemed')}catch(e){setError(e instanceof Error?e.message:'No pudimos canjear el código.')}finally{setBusy('')} }
  return <section className="pricing-page"><div className="page-hero compact"><p className="eyebrow">DOS FORMAS DE CREAR</p><h1>Tu herramienta.<br/><em>Tu elección.</em></h1><p>Compra PULSO Studio una vez y usa tu propia clave, o suma Cloud cuando quieras consumo administrado.</p></div>
    <div className="pricing-grid">
      <article className="price-card"><div><p className="eyebrow">PULSO STUDIO</p><h2>US$120<small> pago único</small></h2><p>Licencia perpetua para dos equipos y 12 meses de actualizaciones.</p></div><ul><li>✓ Motor completo de composición</li><li>✓ VST3 + aplicación standalone</li><li>✓ Crear en Ableton Live</li><li>✓ Tu propia clave de IA, bajo tu control</li></ul><button className="button" disabled={!!busy||user?.studioOwned} onClick={()=>void buy('studio')}>{user?.studioOwned?'Ya es tuyo':busy==='studio'?'Conectando…':'Comprar Studio'}</button></article>
      <article className="price-card"><div><p className="eyebrow">PULSO CLOUD · PRÓXIMAMENTE</p><h2>{plans?.monthly?money(plans.monthly.amount,plans.monthly.currency):'En desarrollo'}{plans?.monthly&&<small>/mes</small>}</h2><p>Servicio opcional de créditos, modelos administrados y sincronización. Se habilitará cuando el gateway de IA esté auditado.</p></div><ul><li>✓ Todo el flujo de Studio</li><li>✓ Consumo de IA administrado</li><li>✓ Límites de costo visibles</li><li>✓ Facturación centralizada</li></ul><button className="button button-ghost" disabled>Próximamente</button></article>
    </div>
    <section className="promotion-panel" aria-labelledby="promotion-title"><div><p className="eyebrow">CÓDIGO DE ACCESO O DESCUENTO</p><h2 id="promotion-title">Una invitación también abre la puerta.</h2><p>Ingresa el código que recibiste. Los descuentos comerciales se aplican de forma segura en Stripe y las invitaciones activan el acceso desde tu cuenta.</p></div><div className="promotion-form"><label htmlFor="promotion-code">Código</label><input id="promotion-code" value={promotionCode} onChange={event=>setPromotionCode(event.target.value)} maxLength={64} autoComplete="off" placeholder="Ej. CAB1@4"/><div className="promotion-actions"><button className="button button-ghost" disabled={!promotionCode.trim()||!!busy} onClick={()=>void redeem()}>{busy==='promo'?'Canjeando…':'Canjear acceso'}</button><button className="text-button" disabled={!promotionCode.trim()||!!busy} onClick={()=>void buy('studio')}>Aplicar a Studio</button></div>{promoMessage&&<p className="form-success" role="status">{promoMessage}</p>}</div></section>
    {error&&<p className="form-error pricing-note" role="alert">{error}</p>}<p className="pricing-note">Stripe procesa pagos, impuestos, facturas y medios de pago. PULSO no almacena datos de tarjeta.</p></section>
}
