name: CI

on:
  push:
  pull_request:

jobs:
  core:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure core
        run: cmake -S . -B build/core -DPULSO_BUILD_PLUGIN=OFF
      - name: Build core
        run: cmake --build build/core --config Release --parallel
      - name: Test core
        run: ctest --test-dir build/core -C Release --output-on-failure

  plugin:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure plugin
        run: cmake -S . -B build/plugin -DPULSO_BUILD_PLUGIN=ON
      - name: Build plugin
        run: cmake --build build/plugin --config Release --parallel
      - name: Test plugin
        run: ctest --test-dir build/plugin -C Release --output-on-failure
        
      # CD: Guardar el artefacto final para poder descargarlo
      - name: Upload VST3 Plugin
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: AtomPulses-Windows-VST3
          path: "**/*.vst3"